In [43]:
import requests
from bs4 import BeautifulSoup
import pandas as pd


def get_table(url):
    response = requests.get(url)

    # Parse the HTML content
    soup = BeautifulSoup(response.text, 'html.parser')

    tables = soup.find_all('table', {'cellpadding': '3', 'cellspacing': '1', 'class': 'standard_tabelle'})
    table = tables[0]

    rows = table.find_all('tr')
    # Iterate over each row
    df_all = pd.DataFrame()
    for row in rows:
        df = pd.DataFrame({'date': [row.find_all('td')[0].text.strip()],
                           'time': [row.find_all('td')[1].text.strip()],
                           'team1': [row.find_all('td')[2].text.strip()],
                           'team2': [row.find_all('td')[4].text.strip()],
                           'score': [row.find_all('td')[5].text.strip()]})
        df_all = pd.concat([df_all, df])
        
    return df_all

df_all = pd.DataFrame()

n=38
for i in range(1, n+1):
    print(f"Scraping page {i} out of {n}.")
    url = f"https://www.worldfootball.net/schedule/ita-serie-a-2023-2024-spieltag/{i}/"
    df_all = pd.concat([df_all, get_table(url)])


df_all

Scraping page 1 out of 38.
Scraping page 2 out of 38.
Scraping page 3 out of 38.
Scraping page 4 out of 38.
Scraping page 5 out of 38.
Scraping page 6 out of 38.
Scraping page 7 out of 38.
Scraping page 8 out of 38.
Scraping page 9 out of 38.
Scraping page 10 out of 38.
Scraping page 11 out of 38.
Scraping page 12 out of 38.
Scraping page 13 out of 38.
Scraping page 14 out of 38.
Scraping page 15 out of 38.
Scraping page 16 out of 38.
Scraping page 17 out of 38.
Scraping page 18 out of 38.
Scraping page 19 out of 38.
Scraping page 20 out of 38.
Scraping page 21 out of 38.
Scraping page 22 out of 38.
Scraping page 23 out of 38.
Scraping page 24 out of 38.
Scraping page 25 out of 38.
Scraping page 26 out of 38.
Scraping page 27 out of 38.
Scraping page 28 out of 38.
Scraping page 29 out of 38.
Scraping page 30 out of 38.
Scraping page 31 out of 38.
Scraping page 32 out of 38.
Scraping page 33 out of 38.
Scraping page 34 out of 38.
Scraping page 35 out of 38.
Scraping page 36 out of 38.
Scraping page 37 out of 38.
Scraping page 38 out of 38.

          date   time             team1                team2      score
0   19/08/2023  17:30         Empoli FC        Hellas Verona  0:1 (0:0)
0               17:30  Frosinone Calcio           SSC Napoli  1:3 (1:2)
0               19:45         Genoa CFC       ACF Fiorentina  1:4 (0:3)
0               19:45             Inter             AC Monza  2:0 (1:0)
0   20/08/2023  17:30           AS Roma  US Salernitana 1919  2:2 (1:1)
..         ...    ...               ...                  ...        ...
0                         Hellas Verona                Inter        -:-
0                              Juventus             AC Monza        -:-
0                            Lazio Roma      Sassuolo Calcio        -:-
0                              AC Milan  US Salernitana 1919        -:-
0                            SSC Napoli             US Lecce        -:-

[380 rows x 5 columns]